apiVersion: v1
kind: Service
metadata:
  name: traefik-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik-metrics
    powerslide.cloud/infrastructure: 'true'
spec:
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    powerslide.cloud/infrastructure: 'true'
  name: pwrsl-monitoring-traefik
  namespace: pwrsl-monitoring
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 30s
  jobLabel: pwrsl-monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-kube-system
      app.kubernetes.io/name: traefik-metrics
