name: Release
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          # elevated token needed to push 'v*' protected tags
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Set Go Version
        id: go_version
        run: |
          echo "VERSION=$(cat .tool-versions | grep golang | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go_version.outputs.VERSION }}

      - name: Build Release
        env:
          RELEASE_VERSION: ${{ steps.tag_version.outputs.new_version }}
        run: make release

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_version }}
          body: ${{ steps.tag_version.outputs.changelog }}
          files: |
            bin/install.sh
            bin/sha256sums
            bin/pwrsl-linux-386
            bin/pwrsl-linux-amd64
            bin/pwrsl-linux-arm
            bin/pwrsl-linux-arm64
            bin/pwrsl-darwin-amd64
            bin/pwrsl-darwin-arm64
            bin/pwrsl-windows-386.exe
            bin/pwrsl-windows-amd64.exe
            bin/pwrsl-windows-arm.exe
            bin/pwrsl-windows-arm64.exe

      - name: Generate Change Log
        env:
          GH_TOKEN: ${{ github.token }}
        run: make changelog

      - name: Create Change Log PR
        id: pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit-message: 'chore: Update CHANGELOG'
          branch: update-changelog
          delete-branch: true
          base: develop
          labels: |
            changelog
          title: '[Automatic] Update CHANGELOG'
          add-paths: |
            CHANGELOG.md

      - name: Merge Change Log PR
        env:
          GH_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          PR: ${{ steps.pr.outputs.pull-request-number }}
        run: gh pr merge $PR --merge
